services:
  lhc:
    container_name: llama-hosting-clients
    image: liangyiu/lhc
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_POCKETBASE_URL=***REMOVED***
        - REDIS_URI=***REMOVED***
        - POCKETBASE_ADMIN_EMAIL=***REMOVED***
        - POCKETBASE_ADMIN_PW=***REMOVED***
    env_file: .env
    ports:
      - 8080:3000
