services:
  lhc:
    container_name: llama-hosting-clients
    image: liangyiu/lhc
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_POCKETBASE_URL=${PUBLIC_POCKETBASE_URL}
        - REDIS_URI=${REDIS_URI}
        - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
        - POCKETBASE_ADMIN_PW=${POCKETBASE_ADMIN_PW}
    env_file: .env
    ports:
      - 8080:3000
