<script lang="ts">
	// import type { SvelteComponent } from 'svelte';
	// import { getModalStore } from '@skeletonlabs/skeleton';

	interface Props {
		// expose parent props to comp
		parent: SvelteComponent;
	}

	let { parent }: Props = $props();

	// const modalStore = getModalStore();

	// async function handleSubmit() {
	// 	if ($modalStore[0].response) {
	// 		$modalStore[0].response({ confirmed: true, totp_code: totpCode });
	// 		modalStore.close();
	// 	}
	// }

	let totpCode = $state('');

	// Base Classes
	const cBase = 'card p-4 w-modal shadow-xl space-y-4';
	const cHeader = 'text-2xl font-bold';
</script>

<!-- {#if $modalStore[0]}
	<div class="modal-totp-code-entry {cBase}">
		<header class={cHeader}>Enter 2FA/TOTP Code</header>
		<article>Enter the code generated by your authenticator app to continue.</article>

		<div class="border border-surface-500 p-4 space-y-4 rounded-container">
			<label class="label">
				<span>Code</span>
				<input class="input" type="text" bind:value={totpCode} placeholder="Enter TOTP Code" />
			</label>
		</div>

		<footer class="modal-footer {parent.regionFooter}">
			<button class="btn {parent.buttonNeutral}" onclick={parent.onClose}>
				{parent.buttonTextCancel}
			</button>
			<button class="btn {parent.buttonPositive}" onclick={handleSubmit}>
				{parent.buttonTextSubmit}
			</button>
		</footer>
	</div>
{/if} -->
