<script lang="ts">
	import type { SvelteComponent } from 'svelte';
	import { getModalStore } from '@skeletonlabs/skeleton';

	// expose parent props to comp
	export let parent: SvelteComponent;

	const modalStore = getModalStore();

	async function handleSubmit() {
		if ($modalStore[0].response) {
			$modalStore[0].response({ confirmed: true, totp_code: totpCode });
			modalStore.close();
		}
	}

	let totpCode = '';

	// Base Classes
	const cBase = 'card p-4 w-modal shadow-xl space-y-4';
	const cHeader = 'text-2xl font-bold';
</script>

{#if $modalStore[0]}
	<div class="modal-totp-code-entry {cBase}">
		<header class={cHeader}>Enter 2FA/TOTP Code</header>
		<article>Enter the code generated by your authenticator app to continue.</article>

		<div class="border border-surface-500 p-4 space-y-4 rounded-container-token">
			<label class="label">
				<span>Code</span>
				<input class="input" type="text" bind:value={totpCode} placeholder="Enter TOTP Code" />
			</label>
		</div>

		<!-- prettier-ignore -->
		<footer class="modal-footer {parent.regionFooter}">
			<button class="btn {parent.buttonNeutral}" on:click={parent.onClose}>{parent.buttonTextCancel}</button>
			<button class="btn {parent.buttonPositive}" on:click={handleSubmit}>{parent.buttonTextSubmit}</button>
		</footer>
	</div>
{/if}
